---
- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: yes

- name: Restart chrony
  service:
    name: chronyd
    state: restarted
    enabled: yes
