---
extends: default

ignore: |
  /roles/*/templates/

rules:
  document-start: disable
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
  braces:
    max-spaces-inside: 1
  truthy:
    allowed-values: ["yes", "no", "true", "false"]
    check-keys: false
