- name: Check if firewalld is installed
  ansible.builtin.package_facts:
    manager: "auto"

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld' in ansible_facts.packages"

- name: Remove firewalld
  ansible.builtin.package:
    name: firewalld
    state: absent
  when: "'firewalld' in ansible_facts.packages"
